sonar.projectKey=frontend-vite-vue-3
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.test.vue,src/test/**
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.test.vue,src/test/**,src/components/ui/*/index.ts,src/components/ui/DataTable/types.ts,src/main.ts,src/App.vue
sonar.javascript.lcov.reportPaths=coverage/lcov.info
